; ============================================================================
; ĐỒ ÁN 2 - NODE SLAVE
; Cấu hình PlatformIO cho ESP32 DevKit / NodeMCU LuaNode32
; ============================================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    mandulaj/PZEM004Tv30 @ ^1.1.2
